name: Receive CML Publish Event
on:
  repository_dispatch:
    types:
      - new-cml
      - pr

jobs:
  cml-pr:
    if: ${{ github.event.event_type == 'pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: |
          echo "${{ github.event.client_playload.branch }}"
  cml-published:
    if: ${{ github.event.event_type == 'new-cml' }}
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: |
          echo "CML version ${{ github.event.client_payload.tag }}"
