#// https://github.com/iterative/cml/issues/1048
#// https://github.com/iterative/cml/pull/1049
name: cml#1049 Allow Native GPU types
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}
#include "../includes/token.yml"

jobs:
  #define JOB_ID gcp-t4
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/gcp/auth-key.yml"
      #// user's example
      #// https://cloud.google.com/compute/docs/general-purpose-machines#n1-high-memory
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --single \
            --labels=LABEL \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=n1-highmem-2 \
            --cloud-spot \
            --cloud-gpu=nvidia-tesla-t4 \
            --cloud-hdd-size=50

  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      #include "../includes/tests/nvidia.yml"
