#// https://github.com/iterative/cml/issues/1116
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: cml#1116 runner with private ssh key .pem
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

#include "../includes/token.yml"

jobs:
  #define JOB_ID private-key
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Private key
        run: |
          #// ssh-keygen -t rsa -b 2048 -f key.pem -m pem -N ""
          openssl genrsa -out key.pem
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-ssh-private="$(cat ./key.pem) "
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"