#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1
name: cml#1098 Warn Users of timeout-minutes change
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'detect-actions-timeout' }}

#include "../includes/token.yml"

jobs:
  random:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cool job that needs a timeout
        run: |
          echo "doing stuff"
          sleep 120
          echo "done"
  #define JOB_ID check-timeout
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  TEST_JOB_ID-2:
    needs: [JOB_ID]
    timeout-minutes: 400
    runs-on: [self-hosted, LABEL]
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
