#// https://github.com/iterative/cml/pull/1173
#// issue

#define __CML_BRANCH__ publish-sha-hash

name: cml#1173 Custom CML comment watermarks.
on:
  pull_request:
    branches:
      - main
#define __PULL_REQUEST__ true
jobs:
  #define JOB_ID custom_1
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      #define WM_LABEL JOB_ID-wm
      #include "../includes/tests/comment/label.yml"
  #define JOB_ID custom_2
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      #define WM_LABEL JOB_ID-wm
      #include "../includes/tests/comment/label.yml"
  #define JOB_ID workflow_label
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      #define WM_LABEL "{workflow}"
      #include "../includes/tests/comment/label.yml"