name: cml#10XX Advanced pr options
on:
  workflow_dispatch:

#include "../includes/token.yml"
jobs:
  #define TEST_CML_BRANCH cml-pr-opts
  #define JOB_ID advanced-pr
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml-branch.yml"
      #include "../includes/tests/pr-custom.yml"
