#// https://github.com/iterative/cml/issues/1104
#// https://github.com/iterative/cml/issues/1099
#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: cml#1104 runner `--cloud-metadata` parsing
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

#include "../includes/token.yml"

jobs:
  #define JOB_ID metadata
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=__AWS_REGION__ \
            --cloud-metadata="condition one=KeyHasASpace" \
            --cloud-metadata='"condition two"="KeyAndValueAreWrappedWithQuotes"' \
            --cloud-metadata='"condition three"=KeyIsWrappedValueIsNot' \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  inspect:
    needs: [TEST_JOB_ID]
    runs-on: ubuntu-latest
    #include "../includes/environment.yml"
    steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Check Instance tags
        run: |
          aws ec2 describe-instances \
            --filters Name=tag:Name,Values=cml-* \
            --region __AWS_REGION__ \
            | jq '.Reservations[].Instances[] | .Tags'
