#// https://github.com/iterative/cml/issues/575
#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

#define __CML_BRANCH__ debug-1255-1

name: cml#575 Reuse Idle Runners
on:
  #include "../includes/schedule.yml"
  #include "../includes/workflow_dispatch.yml"

#include "../includes/token.yml"

jobs:
  #define JOB_ID reuse-idle
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --cml-version="github:iterative/cml#debug-1255-1" \
            --reuse-idle \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
      - name: Let Idle...
        run: sleep 120
      - name: Create Runner should exit right away
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --cml-version="github:iterative/cml#debug-1255-1" \
            --reuse-idle \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"

  #define JOB_ID negitive-reuse-idle
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --reuse-idle \
            --cml-version="github:iterative/cml#debug-1255-1" \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      - name: Spin for 3 minutes
        run: sleep 180
  TEST_JOB_ID-2:
    needs: [JOB_ID]
    runs-on: ubuntu-latest
    #include "../includes/environment.yml"
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      - name: Spin for 1 minute
        run: sleep 60
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner, previous runner should be busy create new one
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --reuse-idle \
            --cml-version="github:iterative/cml#debug-1255-1" \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  TEST_JOB_ID-3:
    needs: [TEST_JOB_ID-2]
    runs-on: [LABEL]
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
