#// https://github.com/iterative/cml/pull/1202
#// issue
#include "../includes/common_defines.yml"

name: cml#1202 CML Comment on issue
on:
  #include "../includes/workflow_dispatch.yml"

#define __CML_BRANCH__ d003-issue-comments

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      - uses: dacbd/create-issue-action@v1
        id: create-issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test for `cml comment create`
      - run: |
          echo "cml comment create --issue test" > report.md
          cml comment create --issue ${{ steps.create-issue.outputs.number }} ./report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          gh issue view ${{ steps.create-issue.outputs.number }} --comments 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: clean-up
        if: always()
        run: gh issue close ${{ steps.create-issue.outputs.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}