#// https://github.com/iterative/cml/issues/1116
#// https://github.com/iterative/cml/issues/852
#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: cml#1116 runner with private ssh key .pem
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

#include "../includes/token.yml"

jobs:
  #define JOB_ID private-key
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Private key
        run: |
          openssl genrsa -out key.pem
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-ssh-private="$(cat ./key.pem) " \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  #define JOB_ID private-key-852
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Private key
        run: |
          openssl genrsa -out key.pem
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-ssh-private="$(cat ./key.pem)" \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"