#// https://github.com/iterative/cml/pull/1302
#// https://github.com/iterative/cml/issues/1285

#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

#define __CML_BRANCH__ master
name: cml#1303 --cloud-image Usage (aws)
on:
  push:
    branches:
      - cloud-image-test
  #include "../includes/schedule.yml"
  #include "../includes/workflow_dispatch.yml"

#include "../includes/token.yml"

jobs:
  #define JOB_ID aws
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --single \
            --labels=LABEL \
            --cloud=aws \
            --cloud-image="ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20221206" \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      #include "../includes/tests/spin.yml"
