#// https://github.com/iterative/cml/pull/1166
#define NEEDS_AWS true
#define __AWS_REGION__ us-east-1
#include "../includes/common_defines.yml"
name: cml#1166 comment --publish-url self-hosted
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

jobs:
  #include "../includes/aws/self-host-publish-setup.yml"
  #define JOB_ID test
  JOB_ID:
    needs: aws-self-host-setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          CML_COMMENT_PUBLISH_URL: ${{ needs.setup.outputs.url }}
        run: |
          curl "https://avatars.githubusercontent.com/u/1105843?s=400&v=4" --output img1.jpg
          echo "# hello" >> file.md
          echo "![An Image](./img1.jpg)"
          cml comment create --publish file.md
  #include "../includes/aws/self-host-publish-cleanup.yml"