name: Test CML PR usage
on:
  workflow_dispatch:

#include "../includes/token.yml"
jobs:
  #define JOB_ID basic-pr
  #include "../includes/setup.yml"
    #
      #include "../includes/tests/pr-basic.yml"