#// https://github.com/iterative/cml/pull/1345
#// https://github.com/iterative/cml/issues/1344

#include "../includes/common_defines.yml"
#include "../includes/token.yml"

name: cml#1344 `cml pr create` from sub dir
on:
  #include "../includes/schedule.yml"
  #include "../includes/workflow_dispatch.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml.yml"
      - name: cml pr create
        env: 
          REPO_TOKEN: ${{ github.token }}
        run: |
          git pull
          pushd ./misc
          echo "$(date +%s%N) - modification" >> cml.log
          cml pr create --squash .
