#// https://github.com/iterative/cml/issues/1048
#// https://github.com/iterative/cml/pull/1049
#include "../includes/common_defines.yml"
name: cml gcp name
on:
  #include "../includes/schedule.yml"
  push:
    branches:
      - gcp-instance-name
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}
#include "../includes/token.yml"

#define CML_SOURCE master
#define TPI_SOURCE gcp-Name-alias

jobs:
  #define JOB_ID gcp-name
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/gcp/auth-key.yml"
      #// user's example
      #// https://cloud.google.com/compute/docs/general-purpose-machines#n1-high-memory
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __SSH_KEYS__ \
            --single \
            --labels=LABEL \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-metadata="Name=test3" \
            --cloud-type=c2-standard-4

  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      - run: sleep 180
