name: cml#1063 Advanced pr options
on:
  workflow_dispatch:

#include "../includes/token.yml"
jobs:
  #define TEST_CML_BRANCH cml-pr-opts
  #define JOB_ID advanced-pr
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml-branch.yml"
      #include "../includes/tests/pr/custom.yml"
  #define JOB_ID branch-pr
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml-branch.yml"
      #include "../includes/tests/pr/branch.yml"
  #define JOB_ID file-pr
  JOB_ID:
    runs-on: ubuntu-latest
    steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/steps/cml-branch.yml"
      #include "../includes/tests/pr/body.yml"