#// https://github.com/iterative/cml/pull/1233

name: cml#1233 --ci-fetch depth
on:
  workflow_dispatch:

#define __CML_BRANCH__ internal-deepyaman

jobs:
  unshallow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --unshallow
      - name: verify
        run: |
          count=$(git rev-list --all --count)
          echo "$count"
          test $count != 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 0
      - name: verify
        run: |
          count=$(git rev-list --all --count)
          echo "$count"
          test $count != 1
  mid-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 5
      - name: verify
        run: |
          count=$(git rev-list --all --count)
          echo "$count"
          test $count = 5
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci
      - name: verify
        run: |
          count=$(git rev-list --all --count)
          echo "$count"
          test $count = 1
