#// https://github.com/iterative/cml/issues/1065
#// https://github.com/iterative/terraform-provider-iterative/pull/607
#// https://github.com/iterative/terraform-provider-iterative/issues/606

#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: cml#1065 validate gpu functionality (Ampere arch)
on:
  #include "../includes/schedule.yml"
  #include "../includes/workflow_dispatch.yml"

#include "../includes/token.yml"

jobs:
  #define JOB_ID gpu-a10
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --single \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=g5.xlarge
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      #include "../includes/tests/nvidia.yml"
      #include "../includes/tests/spin.yml"
