#define NEEDS_AWS true
#define __AWS_REGION__ us-east-1
#include "../includes/common_defines.yml"
name: cml#1075 Self-Host Publish
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

#include "../includes/token.yml"
jobs:
  setup:
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    #include "../includes/environment.yml"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: iterative/minroud-s3
      - name: Install Deps
        run: npm install --global serverless
      #include "../includes/aws/aws-creds.yml"
      - name: Deploy
        id: deploy
        run: |
          npx serverless deploy
          npx serverless info
          url=$(npx serverless info | awk 'match($0, "endpoint: "){ print substr($0, RSTART + 10)}')
          echo "$url"
          echo "::set-output name=url::$url"
      - uses: actions/upload-artifact@v3
        with:
          name: state
          path: .serverless
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      #include "../includes/steps/cml.yml"
      - name: Test
        env:
          #//CML_PUBLISH_URL: ${{ needs.setup.outputs.url }}
          PUBLISH_URL: ${{ needs.setup.outputs.url }}
        shell: bash -e -x {0}
        run: |
          echo "$PUBLISH_URL"
          echo "Pause for possible debugging, starting in 2 mins"
          sleep 120
          echo "hello" >> file.md
          url=$(cml publish --url=$PUBLISH_URL file.md)
          echo "$url"
          echo "curl-ing:"
          curl "$url"
          test "hello" == $(curl --silent "$url")
  clean-up:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test
    #include "../includes/environment.yml"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: iterative/minroud-s3
      - name: Install Deps
        run: npm install --global serverless
      #include "../includes/aws/aws-creds.yml"
      - uses: actions/download-artifact@v3
        with:
          name: state
          path: .serverless
      - name: Clean up
        run: |
          bucket_name=$(aws s3 ls | awk 'match($0, /minroud/){ print $3}')
          aws s3 rm --recursive "s3://$bucket_name"
          npx serverless remove
