#// https://github.com/iterative/cml/pull/1164
#// https://github.com/iterative/cml/pull/802
#// https://github.com/iterative/terraform-provider-iterative/pull/665

#include "../includes/common_defines.yml"
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: cml#1164 Private ENV secrets
on:
  workflow_dispatch:


#include "../includes/token.yml"
#define CML_SOURCE suggestion/no-envvars
#define TPI_SOURCE sensitive

jobs:
  #define JOB_ID target_avail_zone
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            __LINK_RUN__ \
            __SSH_KEYS__ \
            --single \
            --cml-version=github:iterative/cml#suggestion/no-envvars \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=__AWS_REGION__ \
            --cloud-type=t3.small 
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
      - name: Check ENV
        run: |
          printenv AWS_ACCESS_KEY_ID
          printenv AWS_SECRET_ACCESS_KEY
          printenv AWS_SESSION_TOKEN

