#// https://github.com/iterative/cml/issues/1116
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-2

name: cml#11xx extraneous json
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'extraneous-json' }}

#include "../includes/token.yml"

jobs:
  #define JOB_ID min-extraneous-json
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --single \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=__AWS_REGION__ \
            --cloud-type=t3.small \
            --cloud-aws-security-group=cml-test-sg \
            --cloud-aws-subnet=subnet-5d7ee225
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  #define JOB_ID extraneous-json
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=__AWS_REGION__ \
            --cloud-type=t3.small \
            --cloud-aws-subnet=subnet-5d7ee225 \
            --cloud-aws-security-group=cml-test-sg \
            --cloud-metadata="Testing=true" \
            --cloud-metadata="Team=CML" \
            --cloud-metadata="Environment=Development" \
            --single
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  #define JOB_ID org-extraneous-json
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=__AWS_REGION__ \
            --cloud-type=t3.small \
            --cloud-hdd-size=100 \
            --cloud-spot=true \
            --cloud-aws-subnet=subnet-5d7ee225 \
            --cloud-aws-security-group=cml-test-sg \
            --idle-timeout=1000 \
            --cloud-metadata="Testing=true" \
            --cloud-metadata="Team=CML" \
            --cloud-metadata="Environment=Development" \
            --single
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"