#// https://github.com/iterative/cml/pull/1233

name: cml#1233 --ci-fetch depth
on:
  #include "../includes/schedule.yml"
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string

env:
  TEST_CML_BRANCH:  ${{ inputs.branch || 'master' }}

jobs:
  unshallow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --unshallow
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count != 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 0
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count != 1
  mid-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 10
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count = 10
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      #include "../includes/steps/cml.yml"
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count = 1
