#define COMMENT #
#define SPACE
name: train-my-model
on: [push]
jobs:
  #define JOB_ID train-model
  #include "../includes/setup.yml"
      #include "../includes/steps/python.yml"
      - name: Train Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirments.txt
          python train.py
          SPACE
          COMMENT Create CML report
          cat metrics.txt >> report.md
          cml publish plot.png --md --title 'Confusion Matrix' >> report.md
          cml send-comment report.md