name: GCP - Auth Methods
on:
  workflow_dispatch:

#include "../includes/token.yml"

jobs:
  #define JOB_ID as-env
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #
      #include "../includes/gcp/runner-env.yml"
  #include "../includes/tests/version.yml"

  #define JOB_ID as-file
  #include "../includes/setup.yml"
    #
      #include "../includes/gcp/runner-g-auth.yml"
  #include "../includes/tests/version.yml"

  #define JOB_ID as-oidc
  #include "../includes/setup.yml"
    #
      #include "../includes/gcp/runner-oidc.yml"
  #include "../includes/tests/version.yml"
