#// ref issue/pr?
#define NEEDS_AWS true

name: CML Runner takes multiple jobs
on:
  workflow_dispatch:

#include "../includes/token.yml"
#define COMMENT #
COMMENT Not strictly parallel because of GitHub Actions queuing jobs
COMMENT but logicly parallel via default mechanics of GHA
jobs:
  #define JOB_ID parallel
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  #define TEST_JOB_ID test-JOB_ID-2
  #include "../includes/tests/on-test.yml"
  #// steps:
      #include "../includes/steps/base-checkout.yml"
      - name: Wait
        run: sleep 120
      #include "../includes/tests/cml-version.yml"

  #define JOB_ID sequence
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      #include "../includes/tests/cml-version.yml"
  #define TEST_JOB_ID2 test-JOB_ID-2
  TEST_JOB_ID2:
    needs: [JOB_ID, TEST_JOB_ID]
    runs-on: [self-hosted, LABEL]
    #ifdef NEEDS_AWS
    #include "../includes/environment.yml"
    #endif
    steps:
      #include "../includes/steps/base-checkout.yml"
      - name: Wait
        run: sleep 120
      #include "../includes/tests/cml-version.yml"