#// https://github.com/iterative/setup-dvc/pull/42
#// https://github.com/iterative/setup-dvc/issues/39

name: setup-dvc#42 allow version downgrades
on:
  workflow_dispatch:
  #include "../includes/schedules/daily.yml"

jobs:
  plain:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - run: dvc --version
  control:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - uses: iterative/setup-dvc@v1
      - run: dvc --version
  neg-control:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-dvc@v1
      - run: dvc --version
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-dvc@v1
        with:
          version: '2.9.5'
      - run: dvc --version
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - uses: iterative/setup-dvc@v1
        with:
          version: '2.9.5'
      - run: dvc --version
