name: new cml publish

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: iterative/cml
        ref: ${{ inputs.cml }}
        path: cml
    - name: Hack new cml
      shell: bash
      run: |
       pushd cml
       npm install
       sed -i "s/asset.cml.dev/3a4tytannq4snhuly2hi674oeq0bmmjw.lambda-url.us-east-1.on.aws/g" src/utils.js
       sudo npm install -g .
       popd
    - name:
      run: |
        echo "hello" >> file.md
        cml publish file.md