#// https://github.com/iterative/terraform-provider-iterative/pull/621
#define NEEDS_AWS true
#define __AWS_REGION__ us-west-1

name: tpi#621 APT install lock
on:
  workflow_dispatch:

env:
  TEST_CML_BRANCH: master

#include "../includes/token.yml"
jobs:
  #define JOB_ID aws
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/aws/aws-creds.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --labels=LABEL \
            --cloud=aws \
            --cloud-region=us-west \
            --cloud-type=t3.small
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      - name: Check an APT install
        run: |
          sudo apt-get update
          sudo apt-get install -y glances
          glances --version
      #include "../includes/tests/cml-version.yml"
  #define JOB_ID gcp
  #define TEST_JOB_ID test-JOB_ID
  #define LABEL JOB_ID-test
  #include "../includes/setup.yml"
    #// steps:
      #include "../includes/gcp/auth-key.yml"
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner \
            --single \
            --labels=LABEL \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2
  #include "../includes/tests/on-test.yml"
    #// steps:
      #include "../includes/steps/base-checkout.yml"
      - name: Check an APT install
        run: |
          sudo apt-get update
          sudo apt-get install -y glances
          glances --version
      #include "../includes/tests/cml-version.yml"