name: AWS - Auth Methods
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  negitive-reuse-idle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --reuse-idle --labels=negitive-reuse-idle-test --cloud=aws --cloud-spot --cloud-region=us-west --cloud-type=t3.small
  test-negitive-reuse-idle:
    needs: [negitive-reuse-idle]
    runs-on: [self-hosted, negitive-reuse-idle-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
