name: cml#11xx extraneous json
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'extraneous-json' }}
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  min-extraneous-json:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_BRANCH }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ !env.TEST_CML_BRANCH }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-2
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --single --labels=min-extraneous-json-test --cloud=aws --cloud-region=us-west-2 --cloud-type=t3.small --cloud-aws-security-group=cml-test-sg --cloud-aws-subnet=subnet-5d7ee225
  test-min-extraneous-json:
    needs: [min-extraneous-json]
    runs-on: [self-hosted, min-extraneous-json-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
  extraneous-json:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_BRANCH }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ !env.TEST_CML_BRANCH }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-2
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --labels=extraneous-json-test --cloud=aws --cloud-region=us-west-2 --cloud-type=t3.small --cloud-aws-subnet=subnet-5d7ee225 --cloud-aws-security-group=cml-test-sg --cloud-metadata="Testing=true" --cloud-metadata="Team=CML" --cloud-metadata="Environment=Development" --single
  test-extraneous-json:
    needs: [extraneous-json]
    runs-on: [self-hosted, extraneous-json-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
  org-extraneous-json:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_BRANCH }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ !env.TEST_CML_BRANCH }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-2
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --labels=org-extraneous-json-test --cloud=aws --cloud-region=us-west-2 --cloud-type=t3.small --cloud-hdd-size=100 --cloud-spot=true --cloud-aws-subnet=subnet-5d7ee225 --cloud-aws-security-group=cml-test-sg --idle-timeout=1000 --cloud-metadata="Testing=true" --cloud-metadata="Team=CML" --cloud-metadata="Environment=Development" --single
  test-org-extraneous-json:
    needs: [org-extraneous-json]
    runs-on: [self-hosted, org-extraneous-json-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
