name: cml Test docker registry permissions
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'master' }}
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  gcp-permission-set:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ !env.TEST_CML_VERSION || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --single --labels=gcp-permission-set-test --cloud-permission-set=permission-set-test@cml-gcp-test.iam.gserviceaccount.com,scopes=storage-rw --cloud=gcp --cloud-region=us-west --cloud-type=e2-highcpu-2 --cloud-hdd-size=50
  test-gcp-permission-set:
    needs: [gcp-permission-set]
    runs-on: [self-hosted, gcp-permission-set-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Docker pull
        run: |
          docker pull ghcr.io/iterative/cml:latest
          docker images
      - name: Docker push
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker tag ghcr.io/iterative/cml:latest us-west1-docker.pkg.dev/cml-gcp-test/cml-test/cml:latest
          docker images
          docker push us-west1-docker.pkg.dev/cml-gcp-test/cml-test/cml:latest
