permissions:
  id-token: write
  contents: write
  pull-requests: write
name: cml#1344 `cml pr create` from sub dir
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch cml-pr-create-subdirectories
        id: cml-setup
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#cml-pr-create-subdirectories
      - name: Create Modification
        run: |
          echo "$(date +%s%N) - modication" >> cml.log
      - name: cml pr create
        env:
          REPO_TOKEN: ${{ github.token }}
        run: |
          git status
          git pull
          pushd ./examples
          cml pr create --squash .
