name: cml#1173 Custom CML comment watermarks.
on:
  pull_request:
    branches:
      - main
jobs:
  custom_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo custom_1 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title custom_1-wm ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title custom_1-wm ./comment.md
          fi
  custom_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo custom_2 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title custom_2-wm ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title custom_2-wm ./comment.md
          fi
  workflow_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo workflow_label >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title "{workflow}" ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title "{workflow}" ./comment.md
          fi
