name: cml#1233 --ci-fetch depth
on:
  workflow_dispatch:
jobs:
  unshallow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch internal-deepyaman
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#internal-deepyaman
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --unshallow
      - name: verify
        run: |
          git log --oneline -10
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch internal-deepyaman
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#internal-deepyaman
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 0
      - name: verify
        run: |
          git log --oneline -10
  mid-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch internal-deepyaman
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#internal-deepyaman
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 5
      - name: verify
        run: |
          git log --oneline -10
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch internal-deepyaman
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#internal-deepyaman
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci
      - name: verify
        run: |
          git log --oneline -10
