name: cml#1049 Allow Native GPU types (Pascal arch)
on:
  push:
    branches:
      - failed-example
  schedule:
    - cron: '45 15 * * 1' # Mondays 1545 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  gcp-p100:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch hotfix-hidden-opts
        id: cml-setup
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#hotfix-hidden-opts
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --cloud-startup-script=$(echo 'curl https://github.com/${{ github.actor }}.keys >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --single --labels=gcp-p100-test --cml-version="github:iterative/cml#hotfix-hidden-opts" --cloud=gcp --cloud-region=us-west --cloud-type=n1-highmem-2 --cloud-gpu=nvidia-tesla-p100 --cloud-hdd-size=50
  test-gcp-p100:
    needs: [gcp-p100]
    runs-on: [self-hosted, gcp-p100-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
      - name: Nvidia drivers
        run: |
          nvidia-smi
      - name: Do work
        run: |
          function spin() {
            echo "work for 30"
            timeout --preserve-status 30s bash -c 'md5sum /dev/zero'
          }
          spin || true
          spin || true
