name: cml#1233 --ci-fetch depth
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'master' }}
jobs:
  unshallow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --unshallow
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count != 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 0
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count != 1
  mid-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci --fetch-depth 10
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count = 10
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: cml ci fetch-depth
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml ci
      - name: verify
        run: |
          count=$(git rev-list --count HEAD)
          echo "$count"
          test $count = 1
