publish-sha-hash
name: cml#1173 part 2
on:
  pull_request:
    branches:
      - main
jobs:
  workflow_label_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Test a CML Branch
        id: cml-setup
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ inputs.branch || __CML_DEFAULT_BRANCH__ }}
      - name: Standard CML setup
        if: ${{ steps.cml-setup.outcome != 'success' }}
        uses: iterative/setup-cml@v1
        with:
          version: latest
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo workflow_label_2 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title "{workflow}" ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title "{workflow}" ./comment.md
          fi
