name: cml#1173 Custom CML comment watermarks.
on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - '**1241.txt'
env:
   REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  custom_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch d009-comment-target
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#d009-comment-target
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo custom_1 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title WM_LABEL ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title WM_LABEL ./comment.md
          fi
