name: cml#1173 part 2
on:
  pull_request:
    branches:
      - main
jobs:
  workflow_label_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Using CML Branch d018-watermark-sha
        id: cml-setup
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#d018-watermark-sha
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo workflow_label_2 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --watermark-title "{workflow}" ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --watermark-title "{workflow}" ./comment.md
          fi
