name: cml#1116 runner with private ssh key .pem
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  private-key:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        id: cml-setup
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ inputs.branch || 'master' }}
      - name: Standard CML setup
        if: ${{ steps.cml-setup.outcome != 'success' }}
        uses: iterative/setup-cml@v1
        with:
          version: latest
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-1
      - name: Create Private key
        run: |
          openssl genrsa -out key.pem
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --cloud-metadata="actions_link=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --labels=private-key-test --cloud=aws --cloud-region=us-west --cloud-ssh-private="$(cat ./key.pem) " --cloud-type=t3.small
  test-private-key:
    needs: [private-key]
    runs-on: [self-hosted, private-key-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
  private-key_852:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        id: cml-setup
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ inputs.branch || 'master' }}
      - name: Standard CML setup
        if: ${{ steps.cml-setup.outcome != 'success' }}
        uses: iterative/setup-cml@v1
        with:
          version: latest
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-1
      - name: Create Private key
        run: |
          openssl genrsa -out key.pem
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --cloud-metadata="actions_link=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --labels=private-key_852-test --cloud=aws --cloud-region=us-west --cloud-ssh-private="$(cat ./key.pem)" --cloud-type=t3.small
  test-private-key_852:
    needs: [private-key_852]
    runs-on: [self-hosted, private-key_852-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
