name: cml#1098 Warn Users of timeout-minutes change
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'detect-actions-timeout' }}
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  random:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cool job that needs a timeout
        run: |
          echo "doing stuff"
          sleep 120
          echo "done"
  check-timeout:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_BRANCH }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ !env.TEST_CML_BRANCH }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-1
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --labels=check-timeout-test --cloud=aws --cloud-region=us-west --cloud-type=t3.small
  test-check-timeout:
    needs: [check-timeout]
    runs-on: [self-hosted, check-timeout-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
  test-check-timeout-2:
    needs: [check-timeout]
    timeout-minutes: 400
    runs-on: [self-hosted, check-timeout-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
