name: cml#1303 --cloud-image Usage (gcp)
on:
  push:
    branches:
      - cloud-image-test
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using CML Branch master
        id: cml-setup
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#master
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --single --labels=gcp-test --cloud=gcp --cloud-region=us-west --cloud-image="ubuntu-os-cloud/ubuntu-2204-lts" --cloud-type="e2-highcpu-2"
  test-gcp:
    needs: [gcp]
    runs-on: [self-hosted, gcp-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
      - name: Do work
        run: |
          function spin() {
            echo "work for 30"
            timeout --preserve-status 30s bash -c 'md5sum /dev/zero'
          }
          spin || true
          spin || true
