name: cml#1173 Custom CML comment watermarks.
on:
  pull_request:
    branches:
      - main
jobs:
  custom_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          depth: 0
      - name: Using CML Branch d001-watermark-spaces
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#d001-watermark-spaces
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo custom_1 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --label custom_1-wm ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --label custom_1-wm ./comment.md
          fi
  custom_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          depth: 0
      - name: Using CML Branch d001-watermark-spaces
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#d001-watermark-spaces
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo custom_2 >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --label custom_2-wm ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --label custom_2-wm ./comment.md
          fi
  workflow_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          depth: 0
      - name: Using CML Branch d001-watermark-spaces
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#d001-watermark-spaces
      - name: Create or Update comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Custom Water Mark Test" > ./comment.md
          echo workflow_label >> ./comment.md
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "PR Opened" >> ./comment.md
            cml comment create --pr --label "{workflow}" ./comment.md
          fi
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "PR commit count: $(git rev-list origin/main.. --count)" >> ./comment.md
            cml comment update --pr --label "{workflow}" ./comment.md
          fi
