name: cml#10XX Advanced pr options
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  advanced-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CML
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@4 github:iterative/cml#cml-pr-opts
      - name: Modifiy file for PR
        run: |
          echo "$(date +%s%N) - pr custom" >> cml.log
          echo "$(date +%s%N) - pr custom" >> README.md
      - name: CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr --title test --body="test pr body" --message="my commit message" .
