name: cml Long run testing
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
permissions:
  id-token: write
  contents: write
  pull-requests: write
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'master' }}
jobs:
  long_run:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ !env.TEST_CML_VERSION || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-1
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --reuse-idle --idle-timeout=30min --labels=long_run-test --cloud-metadata="actions_link=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0) --cloud=aws --cloud-region=us-west-1 --cloud-type=t3.small
  test-long_run:
    needs: [long_run]
    runs-on: [self-hosted, long_run-test]
    steps:
      - uses: actions/checkout@v3
      - name: CML Version Test
        run: |
          which cml
          cml --version
      - name: spin 1
        run: sleep 900
      - name: spin 2
        run: sleep 900
      - name: spin 3
        run: sleep 900
      - name: spin 4
        run: sleep 900
      - name: spin 5
        run: sleep 900
