name: tpi#621 APT install lock
on:
  schedule:
    - cron: '45 14 * * 1' # Mondays 1445 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: false
        type: string
env:
  TEST_CML_BRANCH: ${{ inputs.branch || 'master' }}
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  aws:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          aws-region: us-west-1
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --labels=aws-test --cloud=aws --cloud-region=us-west --cloud-type=t3.small
  test-aws:
    needs: [aws]
    runs-on: [self-hosted, aws-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Check an APT install
        run: |
          sudo apt-get update
          sudo apt-get install -y glances
          glances --version
      - name: CML Version Test
        run: |
          which cml
          cml --version
  gcp:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test a CML Branch
        if: ${{ env.TEST_CML_VERSION != null || github.event_name != 'schedule' }}
        run: |
          npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@5 github:iterative/cml#${{ env.TEST_CML_BRANCH }}
      - name: Standard CML setup
        if: ${{ env.TEST_CML_VERSION == null || github.event_name == 'schedule' }}
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml runner --single --labels=gcp-test --cloud=gcp --cloud-region=us-west --cloud-type=e2-highcpu-2
  test-gcp:
    needs: [gcp]
    runs-on: [self-hosted, gcp-test]
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Check an APT install
        run: |
          sudo apt-get update
          sudo apt-get install -y glances
          glances --version
      - name: CML Version Test
        run: |
          which cml
          cml --version
